version: '2'

services:
   web:
     image: registry.cosmobile.dev/techaway-web:latest
     restart: always
     environment:
       DB_HOST: ${DB_HOST}
       DB_NAME: techaway-${DB_NAME}
       DB_USER: ${DB_USER}
       DB_PASS: ${DB_PASS}
       ADMIN_USERNAME: ${ADMIN_USERNAME}
       ADMIN_PASSWORD: ${ADMIN_PASSWORD}
