version: '2.4'

services:
  techaway:
    image: registry.cosmobile.dev/techaway-web:latest
    restart: always
    labels:
      - "traefik.http.services.${COMPANY_NAME}.loadbalancer.server.port=80"
      - "traefik.http.routers.${COMPANY_NAME}.entrypoints=web"
      - "traefik.http.routers.${COMPANY_NAME}.rule=Host(`${COMPANY_NAME}.techaway.isildur.cosmobile.net`)"
    environment:
      DB_HOST: ${DB_HOST}
      DB_NAME: ${COMPANY_NAME}-techaway
      DB_USER: ${COMPANY_NAME}
      DB_PASS: ${DB_PASS}
    networks:
      - default
      
  migration_caller:
    image: registry.cosmobile.dev/migration_caller:latest
    environment:
      MIGRATION_URL: http://internal.automator.isildur.cosmobile.net/migration
      TOPIC: tech-away
      DB_HOST: ${DB_HOST}
      DB_NAME: ${COMPANY_NAME}-techaway
      DB_USER: ${COMPANY_NAME}
      DB_PASS: ${DB_PASS}
      ADMIN_USERNAME: ${COMPANY_NAME}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
    networks:
      - default
      
networks:
  default:
    external:
      name: proxy
